/* eslint-disable quote-props */
const images = [
  [
    require('./images/closeOwnership_read.png'),
    require('./images/closeOwnership_unread.png'),
  ],
  [
    require('./images/elysiaNotice_read.png'),
    require('./images/elysiaNotice_unread.png'),
  ],
  [
    require('./images/failKyc_read.png'),
    require('./images/failKyc_unread.png'),
  ],
  [
    require('./images/monthlyReport_read.png'),
    require('./images/monthlyReport_unread.png'),
  ],
  [
  require('./images/newDevice_read.png'),
    require('./images/newDevice_unread.png'),
  ],
  [
    require('./images/productNotice_read.png'),
    require('./images/productNotice_unread.png'),
  ],
  [
    require('./images/profit_read.png'),
    require('./images/profit_unread.png'),
  ],
  [
    require('./images/successKyc_read.png'),
    require('./images/successKyc_unread.png'),
  ],
  [
    require('./images/weeklyReport_read.png'),
    require('./images/weeklyReport_unread.png'),
  ],
  [
    require('./images/next_read.png'),
    require('./images/next_unread.png'),
  ],
];
export default images;
